Update README to show deprecation
byu-oit/awslogin pull request #350
Opened 2021-08-19 22:58 UTC by joanna-hugo

Deprecate this tool, add instructions for alternate solutions.
@Gi60s Do you think this explanation of alternatives is clear and thorough enough?

2021-08-23 15:53 UTC, Gi60s commented on README.md
> +  - Select `Command Line or Programmatic Access` and follow the directions on how to update your local aws config files.
I don't see any instructions here about setting up your configuration file. Maybe put something like this:

For each AWS account that exists you'll need to create a profile configuration in your `.aws/config` file. Each configuration should look like this, replacing `<AWS_ACCOUNT_NAME>` with the actual account name and `<AWS_ACCOUNT_ID>` with the actual account id.

```
[profile <AWS_ACCOUNT_NAME>]
sso_start_url = https://byulogin.awsapps.com/start
sso_region = us-west-2
sso_account_id = <AWS_ACCOUNT_ID>
sso_role_name = PowerUser-<AWS_ACCOUNT_ID>
region = us-west-2
output = json
```

2021-08-23 15:54 UTC, Gi60s requested changes
Other than the comment I already added this looks good, so lets update that and then I'll review again. Thank you.

2021-08-24 20:13 UTC, joanna-hugo commented
I think this looks good, thanks for that clarification.

2021-08-24 20:38 UTC, Gi60s approved these changes

2021-08-24 21:19 UTC, merged